### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by wibi9424** [CharlesThobe/chdman#4]
termux

many requirement successful installed

then run last step for termux

`$cp chdman ~/../usr/bin/.`
result is
 `cp: -r not specified; omitting directory 'chdman'`

and also i dont know what is this chdman for, because readme.md is about how to install,

```
$chdman
No command chdman found, did you mean:
 Command chafa in package chafa
 Command chcon in package coreutils
 Command chem in package groff
 Command kadmin in package krb5
 Command mkd2man in package libsoldout
 Command man in package man
 Command myman in package myman
 Command tfman in package notcurses-tools
 Command pacman in package pacman
 Command cpan in package perl
 Command common in package scala
 Command updmap in package texlive-bin
 Command w3mman in package w3m```

**Comment by charlesthobe** [comment]
Sorry the instructions in the README.md weren't accurate about the installation phase, you are supposed to copy the generated binary that is in the build directory, for you, you're probably supposed to run:
```
cp chdman/build/chdman ~/../usr/bin/.
```
Or follow the new instructions again.

As for what chdman is, you can read [this](https://docs.mamedev.org/tools/chdman.html)
